name: SNMP2MQTT / Addon

on:
  push:
    branches:
      - main

env:
  REGISTRY_IMAGE: ghcr.io/${{ github.repository }}

jobs:
  changes:
    name: Config / Changed
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.changes.outputs.scr }}
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      - name: Check for Changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            scr:
              - 'snmp2mqtt/**'

  new-version:
    name: Version / Changed
    if: ${{ needs.changes.outputs.changes == 'true' }}
    needs: 
      - changes
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-latest-tag.outputs.tag }}
      config: ${{ steps.yaml.outputs.version }}
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      - name: Get Latest Tag
        uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
        with:
          semver_only: true      
      - name: Read Version from Config
        uses: pietrobolcato/action-read-yaml@1.0.0
        id: yaml
        with:
          config: ${{ github.workspace }}/snmp2mqtt/config.yaml

  release:
    name: Release
    if: ${{ needs.new-version.outputs.config != needs.new-version.outputs.version }}
    needs: 
      - new-version
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: SNMP2MQTT Addon v${{ needs.new-version.outputs.config }}
          tag_name: ${{ needs.new-version.outputs.config }}
          generate_release_notes: true

  test:
    name: Test / Build
    if: ${{ needs.changes.outputs.changes == 'true' }}
    needs: 
      - changes
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: snmp2mqtt
          push: false
          load: true
          platforms: linux/amd64
          labels: |
            maintainer=andrewjswan
            org.opencontainers.image.title=snmp2mqtt-addon
            org.opencontainers.image.description=Expose SNMP sensors to MQTT
          tags: ${{env.REGISTRY_IMAGE}}:test
