name: SNMP2MQTT / Addon

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY_IMAGE: ghcr.io/${{ github.repository }}

jobs:
  changes:
    name: Config / Changed
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.changes.outputs.scr }}
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      - name: Check for Changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            scr:
              - 'snmp2mqtt/**'

  new-version:
    name: Version / Changed
    if: ${{ needs.changes.outputs.changes == 'true' }}
    needs: 
      - changes
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-latest-tag.outputs.tag }}
      config: ${{ steps.yaml.outputs.version }}
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      - name: Get Latest Tag
        uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
        with:
          semver_only: true      
      - name: Read Version from Config
        uses: christian-ci/action-yaml-github-output@v2
        id: yaml
        with:
          file_path: ${{ github.workspace }}/snmp2mqtt/config.yaml

  release:
    name: Release
    if: ${{ needs.new-version.outputs.config != needs.new-version.outputs.version }}
    needs: 
      - new-version
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: SNMP2MQTT Addon v${{ needs.new-version.outputs.config }}
          tag_name: ${{ needs.new-version.outputs.config }}
          body: "Changelog: https://github.com/andrewjswan/snmp2mqtt-addon/blob/main/snmp2mqtt/CHANGELOG.md"
          generate_release_notes: true

  test:
    name: Test / Build
    if: ${{ needs.changes.outputs.changes == 'true' }}
    needs: 
      - changes
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
        
      - name: Get information
        id: info
        uses: home-assistant/actions/helpers/info@master
        with:
          path: "./snmp2mqtt"

      - name: Test Build
        uses: home-assistant/builder@master
        with:
          args: |
            --test \
            --all \
            --target addon-folder \
            --docker-hub "ghcr.io/${{ github.repository_owner }}" \
            --addon
