name: SNMP2MQTT / Addon

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY_IMAGE: ghcr.io/${{ github.repository }}

jobs:
  changes:
    name: Config / Changed
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.changes.outputs.scr }}
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Check for Changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            scr:
              - 'snmp2mqtt/**'

  init:
    name: Version / Changed
    if: ${{ needs.changes.outputs.changes == 'true' }}
    needs: 
      - changes
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.get-latest-tag.outputs.tag }}
      version: ${{ steps.yaml.outputs.version }}
      architectures: ${{ steps.info.outputs.architectures }}
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Get Latest Tag
        uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
        with:
          semver_only: true      

      - name: Get Version from Config
        uses: christian-ci/action-yaml-github-output@v2
        id: yaml
        with:
          file_path: ${{ github.workspace }}/snmp2mqtt/config.yaml

      - name: Get Addon Information
        id: info
        uses: home-assistant/actions/helpers/info@master
        with:
          path: "./snmp2mqtt"

  release:
    name: Release
    if: ${{ needs.init.outputs.tag != needs.init.outputs.version }}
    needs: 
      - init
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: "${{ needs.init.outputs.version }}: SNMP2MQTT Addon"
          tag_name: ${{ needs.init.outputs.version }}
          body: "## [Addon Changelog](https://github.com/andrewjswan/snmp2mqtt-addon/blob/main/snmp2mqtt/CHANGELOG.md)"
          generate_release_notes: true

  test:
    name: Test / Build
    if: ${{ needs.changes.outputs.changes == 'true' }}
    needs: 
      - changes
      - init
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: ${{ fromJson(needs.init.outputs.architectures) }}
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
        
      - name: Test Build
        uses: home-assistant/builder@master
        with:
          args: |
            --test \
            --${{ matrix.arch }} \
            --target snmp2mqtt \
            --docker-hub "ghcr.io/${{ github.repository_owner }}" \
            --addon
